config/routes.rb
Rails.application.routes.draw do
  resources :brands, only: [:index, :show] do
	  resources :locations, only: [:index, :show]
	  resources :menu_items, only: [:index, :show]
  end
  ActiveAdmin.routes(self)
  root to: 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :locations, dependent: :destroy
	has_many :menu_items, dependent: :destroy
	has_many :price_levels, dependent: :destroy
	has_many :order_types, dependent: :destroy

	validates :name, uniqueness: true, presence: true # redundant due to database constraints but I like doing it anyway
end

app/models/day_part.rb
class DayPart < ApplicationRecord
  belongs_to :location
  has_many :local_pricings, dependent: :destroy

  validates :name, uniqueness: {scope: :location}, presence: true

  delegate :brand, to: :location
  delegate :full_name, to: :location, prefix: true
  delegate :id, to: :brand, prefix: true

  def full_name
  	"#{location_full_name} - #{name}"
  end
end

app/models/local_pricing.rb
class LocalPricing < ApplicationRecord
	belongs_to :location
  belongs_to :order_type
  belongs_to :price_level
  belongs_to :day_part # optional
  delegate :brand, to: :location

  validates :location, presence: true
  validates :price_level_id, presence: true
  validates :order_type_id, uniqueness: { scope: [:location_id, :day_part_id] }, presence: true
  validates :day_part, uniqueness: {scope: [:location_id, :price_level_id, :order_type_id]} # redundant? 
  validates_each :price_level, :order_type, :day_part do |record, attr, value|
  	record.errors.add(attr, 'must belong to same brand as day part/location') if value and value.brand_id != record.brand.id
  end

  delegate :brand, to: :location
  delegate :full_name, to: :location, prefix: true
  delegate :id, to: :brand, prefix: true
  delegate :name, to: :order_type, prefix: true
  delegate :name, to: :price_level, prefix: true
  delegate :name, to: :day_part, prefix: true, allow_nil: true

  def name
  	"#{order_type.name} - #{day_part.try(:name) || 'anytime'}: #{price_level.name}"
  end

  def full_name
  	"#{location_full_name} - #{name}"
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :brand
  has_many :day_parts, dependent: :destroy
  has_many :local_pricings
  has_many :order_types, through: :local_pricings

  validates :name, uniqueness: {scope: :brand}, presence: true

  delegate :name, to: :brand, prefix: true
  delegate :menu_items, to: :brand

  def full_name
  	"#{brand_name} - #{name}"
  end

  # day parts are only available at a location if there is 
  # at least one local pricing for that day part
  def available_day_parts
  		day_parts.joins(:local_pricings).where('local_pricings.id IS NOT NULL').distinct
  end

  # returns order types that are configured for given day part
  # NOTE: if a location has no price configuration for a given day part
  # then that location is not available for that day part.
  def order_types_for_day_part(day_part)
  	order_types.for_day_part(day_part).or(order_types.day_part_null).distinct
  end

  # returns price level for given order type and day part.
  # if no price level is available for a given day part, returns the first price level for ANY day part
  # if no price level is available for that order type, returns nil
  # (note: the spec is ambiguous on this point - 
  # if there is no price level configured for that day part,
  # is that day part available for that order type at all?  I'm assuming yes.)
  def price_level_for_order_type_and_day_part(order_type, day_part)
  	pls = local_pricings.where(order_type_id: order_type, day_part_id: day_part)
  	pls = local_pricings.where(order_type_id: order_type) if pls.empty?
		pls.first
  end

  # TODO - NOT IMPLEMENTED
  # this would/could probably be much more efficient that the present per-item fetch
  def menu_for_order_type_and_day_part(order_type, day_part)
  	# TODO
  	# sketch
  	MenuItem.joins(	brand_id: brand, prices: { price_level: { local_pricings: { day_part_id: [day_part, nil] }, order_type_id: order_type } } )
  end
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :brand
  has_many :price_levels, through: :brand
  has_many :prices, dependent: :destroy

  validates :name, uniqueness: {scope: :brand}, presence: true

  delegate :name, to: :brand, prefix: true

  accepts_nested_attributes_for :prices, allow_destroy: true

  def full_name
  	"#{brand_name} - #{name}"
  end

  # From spec:
  # If the Menu Item has a price specified for the Price Level that correlates with the current Order Type and Day Part, use that Price Level.
  # Else, if the Menu Item has a price specified for the Price Level that correlates with the current Order Type, use that Price Level.
  # Otherwise, the Menu Item has no currently applicable Price Level and cannot be purchased.
  # NOTE: it would seem more natural to find a local_pricing where day part is NULL, but that does not appear to be what the spec says

  # TODO this would be more efficient in a menu fetch method on Location for given order type/day part

  # determine if item is available at location for order type and day part
  def available_at_location_for_order_type_and_day_part?(location, order_type, day_part)
    !price_at_location_for_order_type_and_day_part(location, order_type, day_part).nil?
  end

  # find price for item at given location/order_type/day part
  def price_at_location_for_order_type_and_day_part(location, order_type, day_part)
    possible_prices = prices.for_location_and_order_type_and_day_part(location, order_type, day_part)
    possible_prices = prices.for_location_and_order_type(location, order_type) if possible_prices.empty?
    possible_prices.first
  end
end

app/models/order_type.rb
class OrderType < ApplicationRecord
  belongs_to :brand
  has_many :local_pricings, dependent: :destroy

  validates :name, uniqueness: {scope: :brand}, presence: true

  delegate :name, to: :brand, prefix: true

  scope :for_day_part, -> (day_part) { joins(:local_pricings).where( local_pricings: { day_part: day_part }) } 
  scope :day_part_null, -> { for_day_part(nil) }

  def full_name
  	"#{brand_name} - #{name}"
  end
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :menu_item
  belongs_to :price_level

  validates :amount, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :price_level_id, uniqueness: { scope: :menu_item_id }
  validates_each :price_level do |record, attr, value|
  	record.errors.add(attr, 'must belong to same brand as menu item') unless value and value.brand_id == record.menu_item.brand_id # todo LOD
  end

  delegate :name, to: :menu_item, prefix: :true
  delegate :name, to: :price_level, prefix: :true

  scope :for_location_and_order_type, -> (location, order_type) { joins(price_level: :local_pricings).
			    where(price_level: { local_pricings: { order_type_id: order_type.id, location_id: location.id } }) 
	}
  scope :for_location_and_order_type_and_day_part, -> (location, order_type, day_part) {
  				for_location_and_order_type(location, order_type).where(price_level: { local_pricings: { day_part_id: day_part.id } })
  }
end

app/models/price_level.rb
class PriceLevel < ApplicationRecord
  belongs_to :brand
  has_many :prices, dependent: :destroy
  has_many :local_pricings, dependent: :destroy

  validates :name, uniqueness: {scope: :brand}, presence: true

  delegate :name, to: :brand, prefix: true

  def full_name
  	"#{brand_name} - #{name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < InheritedResources::Base
end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base
	belongs_to :brand

	def show
		@brand = resource.brand
		@day_parts = resource.available_day_parts
		@day_part = params.key?(:day_part) ? @day_parts.where(id: params[:day_part]).first : @day_parts.first
		@order_types = resource.order_types_for_day_part(@day_part)
		@menu_items = resource.menu_items
	end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < InheritedResources::Base
	belongs_to :brand
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/day_parts_helper.rb
module DayPartsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_types_helper.rb
module OrderTypesHelper
end

app/helpers/price_levels_helper.rb
module PriceLevelsHelper
end

app/views/brands/_brand.html.slim
li= link_to brand.name, brand

app/views/brands/index.html.slim
h1 Our brands

ul= render @brands

app/views/brands/show.html.slim
h1= @brand.name

h2 Locations
ul= render @brand.locations

h2 Menu Items
ul= render @brand.menu_items

= link_to 'Locations', brand_locations_path(@brand)
'  |
= link_to 'Menu Items', brand_menu_items_path(@brand)
'  |
= link_to 'Back', brands_path

app/views/locations/_location.html.slim
li= link_to location.name, brand_location_path(location.brand, location)

app/views/locations/index.html.slim
h1
  = link_to parent.name, parent
  '  locations

ul= render @locations

app/views/locations/show.html.slim
- content_for :title, @location.full_name
h1= @location.full_name

ul.nav.nav-pills.float-xs-right.small
	- @day_parts.each do |day_part|
		li.nav-item= link_to day_part.name, brand_location_path(@brand, @location, day_part: day_part), class: ['nav-link', ('active' if day_part == @day_part)]
h3 #{@day_part.name.titleize} Menu

/ TODO move menu find into controller/model
ul.nav.nav-tabs
	- first = true
	- @order_types.each do |order_type|
		li.nav-item
			= link_to order_type.name, "##{order_type.name.parameterize}", data: {toggle: :tab}, role: :tab, class: ['nav-link', ('active' if first)]
			- first = false # why yes, this is kind of sleazy.
.tab-content
	- first = true
	- @order_types.each do |order_type|
		.tab-pane.fade id=order_type.name.parameterize role='tabpanel' class=('active in' if first)
			table.table.table-inverse.table-hover
				tbody
					- @menu_items.each do |menu_item|
						- if menu_item.available_at_location_for_order_type_and_day_part?(@location, order_type, @day_part)
							tr
								td= menu_item.name
								td.text-xs-right= number_to_currency menu_item.price_at_location_for_order_type_and_day_part(@location, order_type, @day_part).amount rescue '-'
		- first = false # more sleaze

= link_to "back to #{@brand.name}", @location.brand

app/views/menu_items/_menu_item.html.slim
li= link_to menu_item.name, brand_menu_item_path(menu_item.brand, menu_item)

app/views/menu_items/index.html.slim
h1
  = link_to parent.name, parent
  '  Menu Items

ul= render @menu_items

app/views/menu_items/show.html.slim
h1= @menu_item.full_name

= link_to "back to #{@menu_item.brand_name}", @menu_item.brand

app/views/visitors/index.html.slim
.page-header
	h1 
		' Welcome to pseudo-Salido
	small 
		' Not officially affiliated with 
		= link_to 'Salido', 'http://salido.com'
ul= render Brand.all